site_name: Cat Foster Care User Guide
site_url: https://natkees.github.io/site
theme:
    name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  icon:
      admonition:
      <type>: <icon>
theme:
  palette:
    primary: brown
theme:
  palette:
    accent: amber
nav:
  - Welcome!: 'index.md'
  - Expectations: 'section1.md'
  - Section2: 'section2.md'
  - Bringing Your Foster Cat Home: 'section3.md'
  - Q&A: 'section4.md'